# Generated by Django 6.0.3 on 2026-03-14 08:20

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('ameria', 'Ամերիա բանկ'), ('evoca', 'Էվոկա բանկ'), ('ineco', 'Ինեկո բանկ'), ('akba', 'Ակբա բանկ')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government', models.CharField(choices=[('ngn', 'Հաշվառման-քննական ստորաբաժանումներ(ՆԳՆ)'), ('arxiv', 'Հայաստանի ազգային արխիվ'), ('kadastr', 'Կադաստրի կոմիտե')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('water', 'Ջրի սպասարկում'), ('energy', 'Հոսանքի սպասարկում'), ('gas', 'Գազի սպասարկում')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telecom', models.CharField(choices=[('viva', 'Վիվասել'), ('team', 'Թիմ'), ('ucom', 'Յուքոմ')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80, unique=True)),
                ('branchCode', models.CharField(max_length=80, null=True, unique=True)),
                ('phone', models.CharField(max_length=100, null=True, unique=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaction', models.CharField(choices=[('qart', 'Քարտերի սպասարկում'), ('vark', 'Վարկ / վարկային գիծ'), ('avand', 'Ավանդներ'), ('kanxik', 'Կանխիկ գործարքներ')], max_length=30, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.bank')),
                ('branch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='bank', chained_model_field='bank', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bankbranch')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80, unique=True)),
                ('branchCode', models.CharField(max_length=80, null=True, unique=True)),
                ('phone', models.CharField(max_length=100, null=True, unique=True)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.government')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governmentaction', models.CharField(choices=[('tesakan', 'Վարորդական վկայական ստանալու տեսական քննություն'), ('gorcnakan', 'Վարորդական վկայական ստանալու գործնական քննություն'), ('dimumH', 'Դիմումի հանձնում'), ('dimumS', 'Դիմումի ստացում'), ('pastatuxt', 'Ստանալ փաստաթուղթ')], max_length=30, null=True, unique=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.government')),
                ('branch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='government', chained_model_field='government', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.governmentbranch')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80, null=True)),
                ('branchCode', models.IntegerField(null=True, unique=True)),
                ('address', models.CharField(max_length=80, unique=True)),
                ('phone', models.CharField(max_length=80, null=True, unique=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiontype', models.CharField(choices=[('Jrachapi poxarinum', 'Ջրաչափի փոխարինում, տեղադրում'), ('Avartakan akti hastatum', 'Ավարտական ակտի հաստատում'), ('Hashvichi poxarinum', 'Հաշվիչի փոխարինում / տեղակայում'), ('Hzorutyan poxarinum', 'Հզորության փոխարինում'), ('Gazi sarqi poxarinum', 'Գազի սարքի փոխարինում, տեղադրում')], max_length=100, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.service')),
                ('branch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='service', chained_model_field='service', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicebranch')),
            ],
        ),
        migrations.CreateModel(
            name='TelecomBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80, unique=True)),
                ('branchCode', models.CharField(max_length=80, null=True, unique=True)),
                ('phone', models.CharField(max_length=100, null=True, unique=True)),
                ('telecom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.telecom')),
            ],
        ),
        migrations.CreateModel(
            name='TelecomAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telecomaction', models.CharField(choices=[('bajanord', 'Դառնալ բաժանորդ'), ('vcharum', 'Վճարումներ'), ('aqsesuar', 'Հեռախոսների, աքսեսուարների և սարքավորումների ձեռքբերում'), ('xorhrdatvutyun', 'Խորհրդատվություն և աջակցում')], max_length=30, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('telecom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.telecom')),
                ('branch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='telecom', chained_model_field='telecom', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.telecombranch')),
            ],
        ),
    ]
