# Generated by Django 6.0.3 on 2026-04-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=models.SlugField(),
        ),
    ]
