# Generated by Django 6.0.3 on 2026-04-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='feature_1_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='feature_1_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='feature_2_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='feature_2_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='feature_3_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='feature_3_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='header_title',
            field=models.CharField(default='Seamless Connection', max_length=255),
        ),
    ]
