# Generated by Django 6.0.3 on 2026-03-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verif_code', models.TextField(unique=True)),
                ('image', models.ImageField(upload_to='qr_codes/')),
              
            ],
        ),
    ]
