# Generated by Django 6.0.3 on 2026-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen', models.CharField(max_length=255, null=True)),
                ('gmail', models.EmailField(max_length=255, null=True)),
                ('verif_code', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
