# Generated by Django 6.0.3 on 2026-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_delete_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Customer', 'Հաճախորդ'), ('Partner', 'Գործընկեր')], max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80, null=True, unique=True)),
                ('message', models.CharField(max_length=222)),
                ('company', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
