# Generated by Django 6.0.3 on 2026-03-26 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='verif_code',
            new_name='text',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
