# Generated by Django 6.0.3 on 2026-03-31 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_verif_code_qrcode_text_qrcode_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('images', models.TextField(help_text='Paste PNG path here')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='bank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/bank/'),
        ),
        migrations.AddField(
            model_name='government',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/government/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/qr_codes/'),
        ),
        migrations.AddField(
            model_name='telecom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/telecom/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to='media/qr_codes/'),
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='core.category')),
            ],
        ),
    ]
