# Generated by Django 6.0.3 on 2026-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_bank_image_government_image_service_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
