# Generated by Django 6.0.3 on 2026-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_category_images_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='svg_path',
            field=models.TextField(default='M12 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0', help_text="Paste the 'd' attribute string here"),
            preserve_default=False,
        ),
    ]
